# Generated by Django 3.2.8 on 2022-04-10 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='inviter'),
        ),
        migrations.AddField(
            model_name='user',
            name='special',
            field=models.BooleanField(default=False, verbose_name='special'),
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='primary')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title', verbose_name='title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='titles',
            field=models.ManyToManyField(through='users.UserTitle', to='titles.Title', verbose_name='titles'),
        ),
    ]
