# Generated by Django 3.2.8 on 2021-12-14 09:34

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='slug')),
                ('cover', models.ImageField(blank=True, upload_to='', verbose_name='cover')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
