# Generated by Django 3.2.8 on 2021-12-18 06:48

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_notes_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='slug')),
                ('cover', models.ImageField(blank=True, upload_to=nodes.models.node_cover_path, verbose_name='cover')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nodes.node', verbose_name='parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
