# Generated by Django 3.2.8 on 2021-12-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_auto_20211218_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'node', 'verbose_name_plural': 'nodes'},
        ),
    ]
