# Generated by Django 3.2.8 on 2021-12-24 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0003_auto_20211218_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('pinned', models.IntegerField(default=0, verbose_name='pinned')),
                ('highlighted', models.IntegerField(default=0, verbose_name='highlighted')),
                ('deleted', models.IntegerField(default=0, verbose_name='deleted')),
                ('edited_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor=models.TextField(blank=True, verbose_name='body'), verbose_name='edited_at')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
