# Generated by Django 3.2.8 on 2022-04-10 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='code')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expire at')),
                ('valid', models.BooleanField(default=True, editable=False, verbose_name='valid')),
                ('invalidated_at', models.DateTimeField(blank=True, null=True, verbose_name='invalidated at')),
                ('special', models.BooleanField(default=False, verbose_name='special')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('invitee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to=settings.AUTH_USER_MODEL, verbose_name='invitee')),
                ('titles', models.ManyToManyField(blank=True, to='titles.Title')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
            },
        ),
    ]
